//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllProjectCombine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalDBEntities : DbContext
    {
        public FinalDBEntities()
            : base("name=FinalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course_detail> course_detail { get; set; }
        public virtual DbSet<employee1> employee1 { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<facultyDetail> facultyDetails { get; set; }
        public virtual DbSet<joinendEmployee> joinendEmployees { get; set; }
        public virtual DbSet<purchase_table> purchase_table { get; set; }
        public virtual DbSet<purchaseProductTable> purchaseProductTables { get; set; }
        public virtual DbSet<purchaseTable> purchaseTables { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<result> results { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student1> students1 { get; set; }
        public virtual DbSet<facultyList> facultyLists { get; set; }
    }
}
