//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllProjectCombine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseTable
    {
        public int purchase_id { get; set; }
        public int purchase_number { get; set; }
        public System.DateTime purchase_date { get; set; }
        public double total_amount { get; set; }
    }
}
